### ISSUE TITLE
Debian package expects non-existent dependency (Ubuntu 22.04)

### ISSUE THREAD

**Issue by youngdjn** [CharlesLehnen/QGIS_KML_to_DJI_Pilot_2#1]
Thanks so much for making this critical tool! And the Debian installer!

Unfortunately I got a dependency error which, from a little googling, seems like it will be addressed by me upgrading to Ubuntu 24.04 (once it becomes stable). The dependency is GLIBC_2.38, but Ubuntu 22.04 uses GLIBC_2.35. I'm sure this works with current Debian, and I know you can't support all distros, plus Ubuntu 24.04 (which I expect uses the newer GLIBC) will be stable soon and then I'll upgrade. So feel free to close this issue. But in case you're curious, here is my error.

```
(base) derek@madrone:~$ QGIS-KML-to-DJI-Pilot-2 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "tkinter/__init__.py", line 38, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIHCJayE/libX11.so.6)
[PYI-37796:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Comment by CharlesLehnen** [comment]
I compiled it on a laptop running Linux Mint 22, which is based on Ubuntu 24.04 LTS, so I think you are right. I tested it on that device and the Debian Package worked great, so hopefully when you update your Ubuntu Distro it works smoothly for you! Let me know if that is not the case

**Comment by youngdjn** [comment]
Hey Charles! I've since upgraded to Ubuntu 24 and can confirm this tools works great. It is a critical part of my workflow. Thanks a ton for making it.
